# Generated by Django 5.1.1 on 2024-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
