# Generated by Django 5.1.1 on 2024-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_app', '0004_ticketregistration_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketregistration',
            old_name='ticket_file',
            new_name='ticket_secure_url',
        ),
    ]
