# Generated by Django 5.1.1 on 2024-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_app', '0005_rename_ticket_file_ticketregistration_ticket_secure_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketregistration',
            name='ticket_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
