# Generated by Django 5.1.1 on 2024-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_app', '0006_ticketregistration_ticket_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketregistration',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
