apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
      - name: user
        image: dhinucphilip/user-meetmingle
        command: ['python', 'manage.py', 'migrate']
        envFrom:
        - configMapRef:
            name: user-configmap
        - secretRef:
            name: user-secret
      restartPolicy: Never
  backoffLimit: 5