apiVersion: v1
kind: Secret
metadata:
  name: user-secret
stringData:
  SECRET_KEY: "django-insecure-kpr_lo!zb(7ky5qjowu3m82d@$*t#$-%eubewss_7frs#c=zb#"
  DATABASE_NAME: "user_service_db"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"
type: Opaque