# Generated by Django 5.1.1 on 2024-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid_in_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
