# Generated by Django 5.1.1 on 2024-11-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_registration_paid_in_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='paid_in_currency',
            new_name='currency',
        ),
    ]
