# Generated by Django 5.1.1 on 2024-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_rename_paid_in_currency_registration_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hoster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
