# Generated by Django 5.1.1 on 2024-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_registration_hoster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
