# Generated by Django 5.1.1 on 2024-11-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
