# Generated by Django 5.1.1 on 2024-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_rename_user_chatmessage_user_id_chatmessage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
