# Generated by Django 5.1.1 on 2024-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatroom_user1_chatroom_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user1_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
