# Generated by Django 5.1.1 on 2024-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='event_promo_videos/'),
        ),
    ]
