# Generated by Django 5.1.1 on 2024-10-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_rename_ticket_required_event_payment_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date_time',
        ),
    ]
