# Generated by Django 5.1.1 on 2024-11-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_banner_image_alter_event_promo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promo_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyparticipant',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
