# Generated by Django 5.1.1 on 2024-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_event_banner_image_alter_event_promo_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_id',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='event',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Waiting for approval', 'Waiting for approval')], default='Waiting for approval', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='approval_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
