# Generated by Django 5.1.1 on 2024-11-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_rename_location_id_event_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='event_app.eventcategory'),
        ),
    ]
