# Generated by Django 5.1.1 on 2024-11-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_eventtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
