# Generated by Django 5.1.1 on 2024-11-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_eventcategory_status_eventcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
