# Generated by Django 5.1.1 on 2024-11-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_alter_eventcategory_name_alter_eventtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status_request',
            field=models.BooleanField(default=False),
        ),
    ]
