# Generated by Django 5.1.1 on 2024-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_event_status_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Draft', 'Draft')], default='Draft', max_length=50),
        ),
    ]
