# Generated by Django 5.1.1 on 2025-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_event_current_participants_count_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='category_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='type_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
